services:
  nginx:
    image: nginx:alpine
    container_name: apt_nginx
    ports:
      - "8080:80"  # Меняем порт на 8080
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - apt_network
    restart: always

  php:
    image: php:8.2-fpm
    container_name: apt_php
    volumes:
      - ./www:/var/www/html
    networks:
      - apt_network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: apt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: apt_db
      MYSQL_USER: apt_user
      MYSQL_PASSWORD: apt123
    ports:
      - "3307:3306"  # Меняем порт на 3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./www/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apt_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: apt_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"  # Меняем порт на 8081
    depends_on:
      - mysql
    networks:
      - apt_network
    restart: always

volumes:
  mysql_data:

networks:
  apt_network:
    driver: bridge
